---
- name: baseline system configuration
  hosts: localhost
  connection: local
  tasks:
    - name: create folders
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - '$HOME/.vim/colors'
        - '$HOME/.vim/undofiles'
        - '$HOME/.vim/swapfiles'
        - '$HOME/.vim/bundle'
        - '$HOME/.bin'
        - '$HOME/.config'
        - '$HOME/src'
        - '$HOME/ansible_stor'
        - '$HOME/docker_stor'
        - '$HOME/certs'